### PR TITLE
[CLI/Core] introduce environment variable support

### LINKED ISSUE #192: Export environment variables to WoT scripts
As mentioned in #190 environment variables are currently not exported to the WoT script context. I guess they might be exported only to privilege scripts since there could be system-specific information there.

### PR DESCRIPTION
**Pull request by relu91**
Closes #192. Notice that this PR is based on  #318. So it will stay in the draft mode until the other is merged.

### CODE REVIEW

**Review by danielpeintner — APPROVED** [review]

**Comment by danielpeintner** [comment]
@egekorkan can you take a look also?

**Comment by egekorkan** [comment]
I have tried and the doing the following did not work:
1. I took the counter example and added the following line after line 127 that says ` Produced ...`
`console.log(process.env.PORT);`
2. I ran the script like the following
`PORT=9000 node ../../packages/cli/dist/cli.js counter.js`
3. I get an output of undefined. However, I can log process.env and prints and empty object, so something definitely works.

**Comment by relu91** [comment]
Environment variables should be defined inside a `.env` file. Just put `PORT=9000` in your current directory `.env` file and it should work.  Looking around it seems a common practice and it has the benefit to not expose EVERY single variable to servient scripts.

**Comment by egekorkan** [comment]
It does :heart_eyes: Can be merged

**Comment by danielpeintner** [comment]
> Environment variables should be defined inside a `.env` file. Just put `PORT=9000` in your current directory `.env` file and it should work. Looking around it seems a common practice and it has the benefit to not expose EVERY single variable to servient scripts.

I wonder whether we should add a description/note saying so...
@relu91 what do you think?

Having said that, I am fine with merging "as is" also.

**Comment by relu91** [comment]
> I wonder whether we should add a description/note saying so...
> @relu91 what do you think?
> Having said that, I am fine with merging "as is" also.

Yeah, I agree. I'm adding some documentation to describe this.

**Comment by relu91** [comment]
Pushed 👍 check if it is sufficient.

**Pull request merged**
