### PR TITLE
chore: Add linting and code style checks to the CI

### PR DESCRIPTION
**Pull request by JKRhb**
This PR is intended to be a follow-up to #493 and adds both a linting action (using eslint) and style check action (using prettier) to the CI. Both actions are currently failing because there the code base is not yet formatted correctly but once #493 is completed all checks will hopefully turn green :)

I am not sure yet, however, if the prettier action is configured correctly (or if it should be swapped out for a similar prettier action) as it does not add annotations in the "files changed" tab yet. I will have a look into that.

### CODE REVIEW

**Comment by JKRhb** [comment]
I just realized that prettier seems to only be able to indicate if a file is not prettified and not which lines are containing style issues. So maybe the state of this PR is already fine.

**Comment by danielpeintner** [comment]
Note: we might still need to do proper linting for packages other than `core`. I would expect to see many minor diffs..

**Comment by JKRhb** [comment]
> Note: we might still need to do proper linting for packages other than `core`. I would expect to see many minor diffs..

Oh, yes, that is true! I think the actions should already check all packages, however.

**Comment by danielpeintner** [comment]
Questions:
* Can we mark eslint issues like warnings only? Not sure.. e.g., https://github.com/bfanger/eslint-plugin-only-warn
* We might want to tweak some errors that are more a warning than an actual error... I think .. i see errors like the following in https://github.com/eclipse/thingweb.node-wot/pull/503/checks?check_run_id=3566959654
  *  Error:    47:9   error    Unexpected var, use let or const instead                               no-var
  *  Error:    97:23  error    ["events"] is better written in dot notation                           dot-notation
  *  Error:   103:7   error    Identifier 'td1_V2' is not in camel case                               camelcase

**Comment by JKRhb** [comment]
> Questions:
> 
> * Can we mark eslint issues like warnings only? Not sure.. e.g., https://github.com/bfanger/eslint-plugin-only-warn

Sure! If we reconfigure eslint to use warnings instead of errors then the annotations should appear as warnings as well. This should also have the positive side-effect of making it unnecessary to change the rules from errors to warnings, by hand :)

By the way: I just realized that @relu91 already included prettier in the eslint config which makes the separate prettier check obsolete, I assume. I would therefore remove it, as it is less precise in pointing out errors anyway.

**Comment by danielpeintner** [comment]
Note: I think we need to describe how anyone can do a local `eslint` check before creating a PR.
I guess we would need to add some documentation in README ...

**Comment by JKRhb** [comment]
> Note: I think we need to describe how anyone can do a local `eslint` check before creating a PR.
> I guess we would need to add some documentation in README ...

Maybe this could be added to `CONTRIBUTING.md`?

**Comment by JKRhb** [comment]
> > Note: I think we need to describe how anyone can do a local `eslint` check before creating a PR.
> > I guess we would need to add some documentation in README ...
> 
> Maybe this could be added to `CONTRIBUTING.md`?

I added a proposal in 9a970f580fbd421769d03b6da962d337731120e4. Feel free to request any changes :)

**Review by relu91 — APPROVED** [review]
PR looks good. The only problem is that eslint actually does not warn you if your file is not well-formatted with prettier (tried locally). Maybe it is a miss-configuration of es-lint. I'll double-check and then we can merge it.

**Comment by relu91** [comment]
Reading [these notes](https://prettier.io/docs/en/integrating-with-linters.html#notes) from the prettier site it seems that is better not to tangle the two tools together. Can you re-add the prettier step in the workflow? We should be able to recognize those annoying end of line and tabs problems.

**Comment by JKRhb** [comment]
> Reading [these notes](https://prettier.io/docs/en/integrating-with-linters.html#notes) from the prettier site it seems that is better not to tangle the two tools together. Can you re-add the prettier step in the workflow? We should be able to recognize those annoying end of line and tabs problems.

Sure, will do :)

**Comment by JKRhb** [comment]
I think the action should work now :) I think there are no annotations but the action gives a "dry" output of what would have been changed and fails if there are any style issues.

**Review by relu91 — APPROVED** [review]
Good for me, merge? @danielpeintner

**Review by danielpeintner — APPROVED** [review]

**Pull request merged**
