### PR TITLE
Update ts types 2022 08 10

### PR DESCRIPTION
**Pull request by danielpeintner**
Almost any update of the JSON schemas causes problems :-( 
see `getModelVersion(...)` in `ThingModelHelpers` this time

### CODE REVIEW

**Comment by danielpeintner** [comment]
I wanted to update `package-lock.json` and run into some issues with OPCUA.
@erossignon do you have an idea?

I do not really understand *why* this can happen since all "node-opcua*" dependencies are set to a fixed version.

```
Error: packages/binding-opcua/src/opcua-protocol-client.ts(113,9): error TS2769: No overload matches this call.
  Overload 1 of 4, '(nodeToBrowse: BrowseDescriptionLike, callback: ResponseCallback<BrowseResult>): void', gave the following error.
    Argument of type '(err: Error | null, browseResult?: BrowseResult) => void' is not assignable to parameter of type 'ResponseCallback<BrowseResult>'.
      Types of parameters 'browseResult' and 'result' are incompatible.
        Type 'import("/home/runner/work/thingweb.node-wot/thingweb.node-wot/node_modules/node-opcua-client/node_modules/node-opcua-types/dist/_generated_opcua_types").BrowseResult' is not assignable to type 'import("/home/runner/work/thingweb.node-wot/thingweb.node-wot/node_modules/node-opcua-types/dist/_generated_opcua_types").BrowseResult'.
          Types of property 'references' are incompatible.
```

**Comment by erossignon** [comment]
Let me check

**Comment by erossignon** [comment]
regenerating the pakcage-lock.json file by deleting it before running npm install again could help you as well.

**Comment by danielpeintner** [comment]
> Let me check

OPCUA issues resolved ... missed to run `npm dedupe`

**Comment by danielpeintner** [comment]
@relu91
the remaining issues relate to ThingModel creation/validation.
* ` "@context": ["http://www.w3.org/ns/td"]` is no longer a valid context for TM
* ...


Do you want to fix them in this PR?
The alternative would be to ignore them for now and fix them in a follow-up PR?

**Comment by relu91** [comment]
> Do you want to fix them in this PR?
The alternative would be to ignore them for now and fix them in a follow-up PR?

Did it now, sorry got messed up and I had to force push.

**Comment by danielpeintner** [comment]
LGTM

**Pull request merged**
