### PR TITLE
fix: improve error handling of unknown interaction name

### PR DESCRIPTION
**Pull request by danielpeintner**
see https://github.com/eclipse/thingweb.node-wot/issues/285

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: the PR has a lot of whitespace diffs due to indentation but the actual change is purely the initial check like

```
            if (!tp) {
                reject(new Error(`ConsumedThing '${this.title}' does not have property ${propertyName}`));
            } else {
```

**Comment by egekorkan** [comment]
:+1: from my side. Since this kind of code is called for every possible interaction, wouldn' t a try/catch be faster? Not sure if it matters and also if based checking is more clear in the code

**Comment by danielpeintner** [comment]
> 👍 from my side. Since this kind of code is called for every possible interaction, wouldn' t a try/catch be faster? Not sure if it matters

Mhh, not sure but I guess try/catch will fail later. So I don't think it is faster

> and also if based checking is more clear in the code

Can you elaborate. I do not really understand what you mean by that...

**Comment by egekorkan** [comment]
> Can you elaborate. I do not really understand what you mean by that...

I just wanted to say to that with if else, it is obvious what error or case is being tested. With try/catch it would be catching anything and assuming it is the error we are interested in.

**Comment by danielpeintner** [comment]
> > Can you elaborate. I do not really understand what you mean by that...
> 
> I just wanted to say to that with if else, it is obvious what error or case is being tested. With try/catch it would be catching anything and assuming it is the error we are interested in.

Either way is fine but the error message in the PR 
`new Error(`ConsumedThing '${this.title}' does not have property ${propertyName}`)`
explicitly mentions the reason that is tested in the `if` statement .... a given interaction name is not available. 

@egekorkan how should we proceed best?

**Comment by egekorkan** [comment]
We can proceed the way it is now, it was just a confusion from my side

**Comment by danielpeintner** [comment]
Great!

**Pull request merged**
