### PR TITLE
chore(coap): update node-coap to version 1.x.x and fix type issues

### PR DESCRIPTION
**Pull request by JKRhb**
This PR updates the `node-coap` dependency to the new major release. There are still a couple of minor issues that have to be resolved first, however (see https://github.com/mcollina/node-coap/pull/322), which is why I opened this PR as a draft for now.

### CODE REVIEW

**Comment by JKRhb** [comment]
The PR is now ready :) Unfortunately, I had to introduce a couple of workarounds as `node-coap` uses the (apparently outdated) `stream` module whose Typescript interfaces are incompatible with the regular Node.JS stream interfaces. I will have a look into replacing this dependency to get rid of the type casting.

As a major addition this PR now features the `close` method on the `Agent` which could be a potential fix for #637.

**Review by relu91 — APPROVED** [review]
LGTM, reminder open an issue to keep track of the type casting after merge.

**Review by danielpeintner — APPROVED** [review]
LGTM

Note1: created https://github.com/eclipse/thingweb.node-wot/issues/642 to keep track of the type-casts

Note2:  #637 is not revolved by this PR 😌

**Comment by JKRhb** [comment]
> LGTM
> 
> Note1: created #642 to keep track of the type-casts

Thank you! :)

> 
> Note2: #637 is not revolved by this PR 😌

Oh, that is unfortunate :( I will have another look into this problem.

**Pull request merged**
