### PR TITLE
refactor: re-introduce server test

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse/thingweb.node-wot/issues/523

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: I am not sure what the commented out client test is meant to do?
@relu91 do you know?

**Comment by relu91** [comment]
If I remember correctly it checks that if another coap server is running on the same port it should throw an error. I remember that we solved this issue in https://github.com/mcollina/node-coap, right @JKRhb? Now I'm wondering if it makes sense to do this test on our package... I think it is more a low-level feature.

**Comment by JKRhb** [comment]
> I remember that we solved this issue in https://github.com/mcollina/node-coap, right @JKRhb?

Yeah, we resolved it in https://github.com/mcollina/node-coap/pull/271/, it has to activated by passing a config parameter (`reuseAddr: false`)  to the server, though. I am also not sure if this should be tested here as it is mostly a behavior of the dependency.

**Comment by danielpeintner** [comment]
Exactly, server test can be re-introduced. That's what this PR is doing.
Having said that, there are also client-tests I am not sure about?

https://github.com/eclipse/thingweb.node-wot/blob/dc99f9a848d4d18dbab8045f062b8e104d2a2c65/packages/binding-coap/test/coap-client-test.ts#L44-L101

**Comment by danielpeintner** [comment]
Is it ok to merge (add the server test again) since node-coap has been fixed by now?

**Comment by JKRhb** [comment]
> Is it ok to merge (add the server test again) since node-coap has been fixed by now?

Hmm, one aspect of what @relu91 and I meant above is that the `EADDRINUSE` error is currently not actually being thrown – removing the try-catch-block does not cause the test to fail. For this we need to add an additional parameter to the `createServer` function in `coap-server.ts`.

**Review by JKRhb — COMMENTED** [review]
If the patch in https://github.com/eclipse/thingweb.node-wot/pull/625#issuecomment-970330832 is applied then these two lines have to removed if I am not mistaken.

Maybe there could also be another assertion added that the `EADDRINUSE` exception is actually being thrown?

**Comment by danielpeintner** [comment]
@JKRhb thanks for you input. Let's wait a bit with this PR since https://github.com/eclipse/thingweb.node-wot/pull/623 also introduces  some *new* tests...

**Comment by danielpeintner** [comment]
@JKRhb do think I shall close this PR. is there any follow-up PR needed?

**Comment by JKRhb** [comment]
Hmm, would you say that the test that has been commented out should be removed? Otherwise I would open a consolidated PR with the suggestions I made above (which should make reviewing them a bit easier).

**Comment by JKRhb** [comment]
I guess one question that needs to be answered in this context is whether it should be allowed to run two server instances in parallel or not.

**Comment by danielpeintner** [comment]
> I guess one question that needs to be answered in this context is whether it should be allowed to run two server instances in parallel or not.

You mean in the *same* instance... with 2 different ports?
I did never try that... neither for other bindings like HTTP...

Running 2 instances separately (with different ports) should just work fine.. or do I miss anything here?

**Comment by JKRhb** [comment]
Oh, no, I actually meant two servers running on the same port. By default, I think this is possible in node-coap but would be disable with the patch I posted above.

**Comment by danielpeintner** [comment]
Ahh, to be honest I don't see benefit in having two servers listening on the same port.. I am surprised this works. Hence, I am OK if this does not work 🙃

@relu91 any opinion... do you have such use-cases ?

**Comment by relu91** [comment]
> Ahh, to be honest I don't see benefit in having two servers listening on the same port.. I am surprised this works. Hence, I am OK if this does not work 🙃
> 
> @relu91 any opinion... do you have such use-cases ?

+1 for throwing when there's already another server listening to the same port. `http` throws therefore I think it is ok to have consistent behavior in node-wot.

**Comment by danielpeintner** [comment]
closed in favor of https://github.com/eclipse/thingweb.node-wot/pull/657

**Pull request closed without merging**
