### PR TITLE
fix: return the object as described in the TD

### PR DESCRIPTION
**Pull request by MartinMeyer1**
The json codec returned the value corresponding to the key "value" of the readed property, instead of the full json object as expected and described in the TD.

Signed-off-by: MartinMeyer1 <meyer.mart@outlook.com>

### CODE REVIEW

**Comment by MartinMeyer1** [comment]
I can't get why this doesn't work on windows...

**Review by danielpeintner — APPROVED** [review]
LGTM.

by now all implementations should no longer use the "wrapper"

**Comment by danielpeintner** [comment]
@MartinMeyer1 can you merge in the changes from master...

**Review by danielpeintner — CHANGES_REQUESTED** [review]
I noticed we have the same wrapper in another codec.

https://github.com/eclipse/thingweb.node-wot/blob/8f30e313d100e19bccd31446ee7fd0013c30e9d4/packages/core/src/codecs/netconf-codec.ts#L47-L52

Can you fix this also as part of this PR. Thanks!

**Review by danielpeintner — APPROVED** [review]
Looks good.

Thanks @MartinMeyer1

**Pull request merged**
