### PR TITLE
chore: update dev version to 0.8.7

### PR DESCRIPTION
**Pull request by danielpeintner**

### CODE REVIEW

**Review by relu91 — COMMENTED** [review]
@danielpeintner there are mysterious additions and deletions in the `package-lock.json` do you know why? can you clean them up?

**Comment by danielpeintner** [comment]
I think you mean that lines like the following lines got removed
"license": "Apache-2.0",
"license": "MIT",
...

To be honest I don't know what happened. I re-created the package-lock.json and they are still not there.
I don't think is an issue tough ... what do you think?

**Comment by danielpeintner** [comment]
@relu91 do you think we can go on with this PR?

**Comment by relu91** [comment]
I'm still a little bit worried to see other random changes in the future, but let's go 😄 .

**Review by relu91 — APPROVED** [review]

**Pull request merged**
