### PR TITLE
Smart coffee machine with oAuth 2.0

### PR DESCRIPTION
**Pull request by fatadel**
This PR creates a new example script combining the existing coffee machine script with oAuth 2.0.

### CODE REVIEW

**Comment by danielpeintner** [comment]
@relu91 may I ask you to check the PR. You seem best suited...

**Comment by fatadel** [comment]
Thank you very much, @relu91!
I agree about a brief readme, but I was adding that information to the tutorial on the thingweb website.
Now it's ready! - https://github.com/eclipse/thingweb.website/pull/17

**Comment by danielpeintner** [comment]
@relu91 if it is OK for you as is I would merge this PR and the PR for the website https://github.com/eclipse/thingweb.website/pull/17

**Comment by relu91** [comment]
I've just noticed that there's also the link to the tutorial inside the source code. Greenlight from my side 👍

**Pull request merged**
