### PR TITLE
fix: properly unsubscribe by stopping HTTP long polling

### PR DESCRIPTION
**Pull request by danielpeintner**
see https://github.com/eclipse/thingweb.node-wot/issues/151

### CODE REVIEW

**Comment by danielpeintner** [comment]
@egekorkan @relu91 May I ask you to take a look at the proposed fix for unsubscribing HTTP events/properties. I did experiment with it and it seems to work fine for me...

@relu91 specifically I think the whole code in `unlinkResource`

https://github.com/eclipse/thingweb.node-wot/blob/7652a56c8d0dbb06b7c558bd52d2c05f47ebb534/packages/binding-http/src/http-client.ts#L145-L161 (other than `this.activeSubscriptions.delete(form.href)`) can be removed. No need to send DELETE to HTTP server because it does not know what to do.. we do HTTP GET (long polling) on client side only? Am I right?

**Comment by relu91** [comment]
I am a little bit puzzled as you. When I refactored the code I thought that sending a delete request was a specification of the `longpoll` protocol.  However, I agree on what @egekorkan is saying in https://github.com/eclipse/thingweb.node-wot/issues/151#issuecomment-558135107. Therefore, I would delete the HTTP request and leave only `this.activeSubscriptions.delete(form.href) `. 

Probably, we should also abort the pending HTTP GET to clean up resources immediately. See this [example on MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort)

**Comment by danielpeintner** [comment]
>  However, I agree on what @egekorkan is saying in [#151 (comment)](https://github.com/eclipse/thingweb.node-wot/issues/151#issuecomment-558135107).

Mhh, not sure. CoAP is different in the way that it supports "observing" as part of the protocol. HTTP does not. @egekorkan ?

> Therefore, I would delete the HTTP request and leave only `this.activeSubscriptions.delete(form.href) `.

Will update the PR accordingly.

**Comment by egekorkan** [comment]
Yes CoAP has it built and this is already fixed no?

**Comment by danielpeintner** [comment]
> Yes CoAP has it built and this is already fixed no?

Yes, see https://github.com/eclipse/thingweb.node-wot/commit/00bbb0df8ba377767ca61e1175c6b5b4a7dee613

**Comment by egekorkan** [comment]
Maybe this also fixed https://github.com/eclipse/thingweb.node-wot/issues/21 ?

**Comment by danielpeintner** [comment]
> Maybe this also fixed #21 ?

Yes, correct. The issue pointed out CoAP which has been fixed before.

**Pull request merged**
