### PR TITLE
fix(examples): fix oauth2 exposer example

### PR DESCRIPTION
**Pull request by JKRhb**
This PR resolves another eslint issue by updating the `wot-thing-description-types` dependency and removing the `@ts-ignore` comment from the OAuth2 exposer example.

### CODE REVIEW

**Comment by relu91** [comment]
Well done I think we should remember when we update `wot-typescript-definitions` like here https://github.com/eclipse/thingweb.node-wot/pull/707 . However, the lastest version is from Febrary: [1.1.0-09-February-2022](https://www.npmjs.com/package/wot-thing-description-types/v/1.1.0-09-February-2022) where are you using an old one?

**Comment by relu91** [comment]
p.s. @danielpeintner what bugs me is that the latest version of wot-typescript-defintions is from 2 days ago, whereas wot-thing-description-types is from February. something is off... isn't it?

**Comment by danielpeintner** [comment]
> However, the lastest version is from Febrary: [1.1.0-09-February-2022](https://www.npmjs.com/package/wot-thing-description-types/v/1.1.0-09-February-2022) where are you using an old one?

Good point. We should use "1.1.0-09-February-2022"

> p.s. @danielpeintner what bugs me is that the latest version of wot-typescript-defintions is from 2 days ago, whereas wot-thing-description-types is from February. something is off... isn't it?

I don't think so.

wot-typescript-definitions@0.8.0-SNAPSHOT.22 was published by my recently since we forgot to push changes on NPM.
wot-thing-description-types@1.1.0-09-February-2022 matches with github [history](https://github.com/w3c/wot-scripting-api/commits/main/typescript/thing-description/package.json)

**Review by danielpeintner — CHANGES_REQUESTED** [review]
Please use 1.1.0-09-February-2022

**Comment by JKRhb** [comment]
> Please use 1.1.0-09-February-2022

Done :) Thank you for noticing!

**Comment by relu91** [comment]
and with this we are eslint errors free🎉🎉 merging.

**Pull request merged**
