### PR TITLE
chore: disable testing for binding-firestore and binding-mbus

### PR DESCRIPTION
**Pull request by danielpeintner**
see issues described in https://github.com/eclipse/thingweb.node-wot/issues/827

### CODE REVIEW

**Comment by relu91** [comment]
I think it is not the test, but firestore dependencies. You have to exclude the package in the workspaces: https://github.com/eclipse/thingweb.node-wot/blob/master/package.json#L37

**Comment by danielpeintner** [comment]
Now mbus is causing issues ?

`npm ERR! path /Users/runner/work/thingweb.node-wot/thingweb.node-wot/node_modules/node-mbus`
see https://github.com/eclipse/thingweb.node-wot/actions/runs/3420221062/jobs/5694753037#step:5:7

**Comment by relu91** [comment]
seems that both packages are using old native libraries that are causing problems?

**Comment by danielpeintner** [comment]
The _funny_ part is that re-running the tests often helps.. this means to me at least it is somewhat temporal !?

**Comment by relu91** [comment]
I excluded firebase also from the building process

**Comment by danielpeintner** [comment]
Mhh, seems not enough. I disabled/excluded mbus also to see whether that helps...

**Comment by relu91** [comment]
> Mhh, seems not enough. I disabled/excluded mbus also to see whether that helps...

There are some people to complain about node-gyp and windows-latest. Maybe [this](https://github.com/actions/setup-node/issues/280#issuecomment-1139752165) can help... but I would defer it since I don't have the bandwidth to try that fix.

**Comment by relu91** [comment]
it is failing again.... maybe it is the Modbus binding. It depends on serialport too. 😢

**Comment by danielpeintner** [comment]
Shall we use `windows-2019` instead of `windows-latest`

**Comment by relu91** [comment]
> Shall we use windows-2019 instead of windows-latest

It would be better to use windows latest but I'm okay with it for focusing on other features.

**Comment by relu91** [comment]
I guess we have to reopen this one: https://github.com/eclipse/thingweb.node-wot/issues/678

**Comment by relu91** [comment]
this chain of failures starts to be creepy 👻 😆 .

**Comment by danielpeintner** [comment]
Yes, very strange... since now mac-os-latest fails with gyp !?

**Comment by danielpeintner** [comment]
let's try `macos-12` instead of `macos-latest` (maybe it helps to use a different [runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)).
Anyhow, VERY VERY strange !?

**Comment by relu91** [comment]
It seems that all the latest runners have some sort of problem with node-gyp... `macos-10.15` is depecrated accordingly to the documentation. What is weird is that I got the same problem with a node alpine docker image today. Maybe it is something broken in the latest npm 8.x.y version? 🤔 .

**Comment by danielpeintner** [comment]
Mhh, I also hope the issues get solved on their own and hence I suggest to use `non-latest` runners do catch actual issues and open a new issue to track this problem? What do people think?

Note: I will try to bring mbus (and firestore) back to see whether the issues are gone also..

**Comment by relu91** [comment]
> Shall we exclude mbus & firestore for now and use the older runners to get at least clean runs for all the PRs?

Yes I think this should be the priority now... let's fix what we can and have an issue to keep track of this problem

**Comment by danielpeintner** [comment]
Closed in favor of https://github.com/eclipse/thingweb.node-wot/pull/878

**Pull request closed without merging**
