### PR TITLE
Npm fix audit

### PR DESCRIPTION
**Pull request by relu91**
**WARNING**: This pr is based on #483

We have accumulated a fair amount of npm auditing errors plus deprecation warnings as explained in #481. This PR tries to solve most of them. Also, it tries to clean up not-used libraries like request in http-binding. 

Current open issues:
- Most of the auditing problems were caused by binding-wotfirestore. I solve them by upgrading to firebase 9. As a consequence now the code is not buildable anymore. I'd ask @hidetak to check what's going on. Meanwhile, the binding is excluded from the package list.
- Even if I upgraded to firebase 9, it seems that firebase-tool is still referencing deprecated versions of `request` which in turn uses a bunch of other deprecated libraries (e.g. uuid 3)
- 3 of the current auditing warnings are caused by [epress-oauth-server](https://www.npmjs.com/package/express-oauth-server). However, there is no new version published yet. The development seems stale to me. This package is needed for testing OAuth 2 implementation. 
- Another warning is given by oracle binding. Specifically, the library iot-csl-js seems to have some old dependencies. It looks like is not open source... probably we can't do anything about it
- Moreover in oracle-binding node-pre-gyp required by sqlite is outdated.

### CODE REVIEW

**Comment by danielpeintner** [comment]
> * Most of the auditing problems were caused by binding-wotfirestore. I solve them by upgrading to firebase 9. As a consequence now the code is not buildable anymore. I'd ask @hidetak to check what's going on. Meanwhile, the binding is excluded from the package list.

Makes sense.
Another alternative is to remove it for now since we had test issues also after the new API changes. The code is available and can be brought back later....

> * 3 of the current auditing warnings are caused by [epress-oauth-server](https://www.npmjs.com/package/express-oauth-server). However, there is no new version published yet. The development seems stale to me. This package is needed for testing OAuth 2 implementation.

Mhh, seems we need to live with it.

 
> * Another warning is given by oracle binding. Specifically, the library iot-csl-js seems to have some old dependencies. It looks like is not open source... probably we can't do anything about it
> 
> * Moreover in oracle-binding node-pre-gyp required by sqlite is outdated.

Maybe it is time to remove oracle-binding from v0.8.x on since development has been stale. We (or anyone else) can still bring it back if here is interest.

**Comment by hidetak** [comment]
@relu91 @danielpeintner 
I apologize for the many audit errors that remain.
I know that this Binding doesn't work in Firebase 8 and above (it can't do Browserify).
I will try to find out if it is possible to prevent the audit error in Firebase 7.

**Comment by relu91** [comment]
> @relu91 @danielpeintner
> I apologize for the many audit errors that remain.

Don't worry 👍🏻  

> I will try to find out if it is possible to prevent the audit error in Firebase 7.

From what I understood, it seems that Firebase 7 was at its lastest version and I don't know if you can really solve those audit issues without upgrading... 😢 On possible solution, to not cluttering node-wot might be to have it published separately and just mention/link the implementation inside the folder.

**Comment by hidetak** [comment]
@relu91 
Thank you for your comment.

> On possible solution, to not cluttering node-wot might be to have it published separately and just mention/link the implementation inside the folder.

Does that mean I should do my own publishing to npm in another repository instead of this one?

I would like to find a way to solve this problem first.
If I can't find a solution, I would be happy to consult with you again.

**Comment by danielpeintner** [comment]
I re-run the tests 3 times on GitHub and we are always getting (different) errors.
* nan.h(56,10): fatal error C1083: Cannot open include file: 'node.h': No such file
* OPCUA failures

Not sure whether it is due the changes or other aspects that are GH-related...

**Review by danielpeintner — APPROVED** [review]
LGTM

**Pull request merged**
