### PR TITLE
fix: OPCUA peerDepencencies issue by adding missing package

### PR DESCRIPTION
**Pull request by erossignon**
* this commit explicitly add packages that appears in the peerDependencies of node-opcua-pubsub-client and node-opcua-json to the package.json of binding-opcua. This is to ensure that the expected versions of those packages will be loaded by npm and prevent conflict.
  * this commit also add specifically rxjs@5.5.11

fixes https://github.com/eclipse-thingweb/node-wot/issues/1012

### CODE REVIEW

**Review by relu91 — COMMENTED** [review]
Are we seeing 0 changes in the root package-lock because those packages are already loaded? or is this a mistake?

**Comment by danielpeintner** [comment]
@erossignon can you merge in updates from master.
https://github.com/eclipse-thingweb/node-wot/pull/1021 should resolve the issues w.r.t. consistency across submodels

**Comment by relu91** [comment]
> Are we seeing 0 changes in the root package-lock because those packages are already loaded? or is this a mistake?

read #1002, see my other comment: https://github.com/eclipse-thingweb/node-wot/issues/1012#issuecomment-1588854262

**Comment by erossignon** [comment]
> Are we seeing 0 changes in the root package-lock because those packages are already loaded? or is this a mistake?

Yes, correct, the top level package.json already includes all necessary packages that are in the peerDepencencies , that is why the problem is not surfacing when the example is run in the context of this module.

Adding the missing modules in binding-opcua makes it work for when binding-opcua is installed standalone.

**Comment by erossignon** [comment]
@danielpeintner , this is now ready to merge.

**Comment by danielpeintner** [comment]
> > Are we seeing 0 changes in the root package-lock because those packages are already loaded? or is this a mistake?
> 
> Yes, correct, the top level package.json already includes all necessary packages that are in the peerDepencencies , that is why the problem is not surfacing when the example is run in the context of this module.
> 
> Adding the missing modules in binding-opcua makes it work for when binding-opcua is installed standalone.

@relu91 are you ok with it?

**Review by relu91 — APPROVED** [review]
I don't want to block the PR so let's move on. But I want to say that (at least to me) it sounds weird to explicitly add the peerDeps in a library package just to simplify the installation for others. It kind of defeats the purpose of the peerDeps. This is also further supported by the fact that in `pnpm ` the problem does not show up (I heard that newer versions of `npm` are better at handling peerDeps). Anyhow, let's merge this.

**Pull request merged**
