### PR TITLE
update version of firestore modules to fix audit warnings

### PR DESCRIPTION
**Pull request by hidetak**
* update version of firestore modules to fix audit warnings
* detached firebase module from `binding-firestore-browser-bundle`

### CODE REVIEW

**Comment by danielpeintner** [comment]
Hi @hidetak. Thanks for your update.

Please not that the working branch v0.8.x is not yet merged into master (this will be the *new* baseline). Hence we will not merge at the moment PRs against the current master. Once branch v0.8.x is properly merged into master we very much like appreciate additions...

**Comment by danielpeintner** [comment]
@hidetak 
FYI  branch `v0.8.x` has been merged into `master`.
Hence all PRs from now on should be against  `master` but i guess it is easier to start a new PR since the base is totally different now.

Note also that firestore has been deactivated because of the issues we had (please remove it from the exclusion)

https://github.com/eclipse/thingweb.node-wot/blob/59fe3264bb4cfa19a3c8cddb0f1c68b4685a4a47/package.json#L25

**Comment by hidetak** [comment]
@danielpeintner 

Thank you for letting me know.
I will check and address the issue and create a new PR.

**Comment by hidetak** [comment]
I'll create another PR again.

**Pull request closed without merging**
