### PR TITLE
chore: use cache in CI

### PR DESCRIPTION
**Pull request by relu91**
This morning I read a Twitter thread from @mcollina, about caching node:_modules to speed up CI runs. Since our runs last already an eternity I think we can try this minor tweak. Let's see if it improves the situation. :)

### CODE REVIEW

**Comment by danielpeintner** [comment]
CI was failing. Restarted them...

**Comment by danielpeintner** [comment]
@relu91 how yo you want to continue with this PR?

**Comment by relu91** [comment]
if of all I would like to understand if it is properly working. I was expecting a considerable boost given the fact that in our repository `npm ci` takes a while. However, I am not seeing such a difference between CI runs:
image
🔝Using cache
image
🔝Without cache

**Comment by relu91** [comment]
Digging deeper, the `cache` option does not cache node_modules but the good news is that in our setup `npm ci` does not take THAT much time. On average the install step takes around 1m. The problem is the test step that takes the most part of the time  ~4min. I think we can improve a little bit by skipping the build in that step since we have already built in the previous one.

**Comment by relu91** [comment]
It seems that the last change didn't improve the execution time either. I guess we just have very slow tests.... 😢

**Comment by danielpeintner** [comment]
@relu91 how should we go on with this PR?

**Comment by relu91** [comment]
> @relu91 how should we go on with this PR?

It does not solve that much but we can merge it. We have a problem with our slow tests. I'll open an issue to keep track of this possible enhancement.

**Pull request merged**
