### PR TITLE
refactor: increase timeout to stabilize MQTT test

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse/thingweb.node-wot/issues/434 ?

### CODE REVIEW

**Comment by danielpeintner** [comment]
let's try whether increasing timeout helps to stabilize the MQTT test on GitHub.
Locally I do not see fails :-(

**Comment by relu91** [comment]
btw I forget to send this PR: https://github.com/relu91/thingweb.node-wot/pull/11 it should solve the issue, it is kinda related to timeouts. Should we use that instead?

**Comment by danielpeintner** [comment]
> btw I forget to send this PR: [relu91#11](https://github.com/relu91/thingweb.node-wot/pull/11) it should solve the issue, it is kinda related to timeouts. Should we use that instead?

Yes, if it fixes the issue, great!
I noticed that https://github.com/relu91/thingweb.node-wot/pull/11/checks?check_run_id=3189248515 fails for CoAP but this might be another issue.

Otherwise I would start to ignore the MQTT test ...

**Comment by danielpeintner** [comment]
For the time being we can also simply *skip* the MQTT test .. that's what it is done in this PR

**Comment by danielpeintner** [comment]
@relu91 @egekorkan since MQTT test are unstable I suggest to *skip* them till we have a solution.
Otherwise we keep **red** flags for all other PRs.

Do you agree?

**Comment by relu91** [comment]
I looked in https://github.com/relu91/thingweb.node-wot/pull/11 it seems that the `coap` problem was just another fluctuation. At least it stabilizes mqtt and opc-ua tests. I'll bring it here and I would favor that one instead of skipping.

**Comment by danielpeintner** [comment]
withdrawn in favor of https://github.com/eclipse/thingweb.node-wot/pull/459

**Pull request closed without merging**
