### PR TITLE
feat(coap): update type definitions

### PR DESCRIPTION
**Pull request by JKRhb**
This PR will update the `binding-coap` package with typescript declarations from `node-coap` (see https://github.com/mcollina/node-coap/pull/278) once a new version is released. It includes my local adjustments used for checking that the type declarations are actually usable. There are a small number of `any`s which still have to be fixed but other than that a large amount of code will be covered now with proper typing.

I also noticed ~~two bugs~~ one minor issue in the `coap` package due to the new type declarations for which I will open a separate PR for an immediate fix.

### CODE REVIEW

**Comment by JKRhb** [comment]
Made some progress, but there is currently still an issue with the "share socket" tests.

**Comment by JKRhb** [comment]
This PR is now ready for review :) I included a commit from @relu91's PR #602 which is why it should probably be merged after it (and after a rebase).

With the merge of this PR, it will be possible to remove the CoAP entry in #534.

**Comment by relu91** [comment]
> This PR is now ready for review :) I included a commit from @relu91's PR #602 which is why it should probably be merged after it (and after a rebase).

Thank you really much! do recommend merging #602 AFTER this PR or the other way around??

**Review by relu91 — APPROVED** [review]
Typing wise looks good! 👍🏻 ready to be merged :)

**Comment by JKRhb** [comment]
> do recommend merging #602 AFTER this PR or the other way around??

Initially I thought we might merge after #602 but we could probably also do it the other way around. I think a couple of problems with the `requestUri` that are dealt with in #602 should already be solved by this PR

**Review by danielpeintner — APPROVED** [review]
I let you decide which PR should be merged first

**Comment by relu91** [comment]
No conflicts after merging #602 :)

**Pull request merged**
