### PR TITLE
fix(binding-opcua tests): fixing tests for binding-opcua

### PR DESCRIPTION
**Pull request by lukesmolo**
I opened this pull request for fixing the tests of binding-opcua. I need some more logs from travis in order to understand what is going on.
Signed-off-by: Lukesmolo <lukesmolo@gmail.com>

### CODE REVIEW

**Comment by danielpeintner** [comment]
Sure, feel free to explore with this PR.

As you might have seen, the error persists...

**Comment by lukesmolo** [comment]
Ok, solved. For some reason, in the third configuration of travis the OPC UA server requires a lot of time to start, so I needed to increment the timeout.

**Comment by lukesmolo** [comment]
Ok, solved. For some reason, in the third configuration of travis the OPC UA server requires a lot of time to start, so I needed to increment the timeout.

**Comment by danielpeintner** [comment]
Thanks

**Pull request merged**
