### PR TITLE
feat: align all files to use "smart-coffee-machine"

### PR DESCRIPTION
**Pull request by danielpeintner**
Note: used to be partly "coffee-machine" only

### CODE REVIEW

**Comment by danielpeintner** [comment]
@fatadel may I ask you to cross check the changes

**Comment by fatadel** [comment]
Seems to be all correct from my side.
The only note is that we will also need to update the tutorial file - https://github.com/fatadel/thingweb.website/blob/master/content/smart-coffee-machine.md.
I can do it myself since anyway I was going to update that tutorial with the new information about the static smart coffee machine page we have added.

**Comment by fatadel** [comment]
@danielpeintner Please take a look at the PR - https://github.com/eclipse/thingweb.node-wot/pull/336.
I've found some naming differences that we haven't spotted in this PR.

**Comment by fatadel** [comment]
I've also updated the tutorial as I said before - https://github.com/eclipse/thingweb.website/pull/23.

**Pull request merged**
