### PR TITLE
Reorganising CLI Readme information

### PR DESCRIPTION
**Pull request by egekorkan**
I am moving CLI readme to its own package's readme and thus tidying up the main one. 

I have started in the web editor but it is not easy to check for prettier etc.

### CODE REVIEW

**Comment by egekorkan** [comment]
Prettier check fails even though I am executing `npm run lint`

**Comment by relu91** [comment]
I think that the CI is not picking our prettier configuration: https://github.com/eclipse/thingweb.node-wot/blob/master/.github/workflows/ci.yaml#L70

**Comment by egekorkan** [comment]
> In my case running `npm run format` locally created some changes, see [bf03fcb](https://github.com/eclipse/thingweb.node-wot/commit/bf03fcba9860c190d1c3a4248e43f2dd762b1366).
> 
> @egekorkan please check whether the result is as expected.

All fine with me:) Also, it seems that the action is not complaining

**Review by danielpeintner — APPROVED** [review]

**Review by relu91 — APPROVED** [review]
LGTM, I'm not sure why the text about log level has been removed, but given the fact that we are going to migrate to "debug" library it should not be a problem. Anyhow we can fix it later. Let's go :)

**Pull request merged**
