### PR TITLE
#363 Fix: Use udp6 for IPv6 and udp4 for legacy IP

### LINKED ISSUE #363: EINVAL error on global IPv6 addresses
I used the [node-wot-boilerplate](https://github.com/Citrullin/wot-node-boilerplate) project. Instead of using a link-local address as mentioned in #362, I used a global IPv6 address. For example `2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54`
When I execute `yarn dev`, I get the following error
```
yarn dev
yarn run v1.22.5
$ ts-node src/index.ts
[core/helpers] Helpers found scheme 'coap'
[core/servient] Servient creating client for scheme 'coap'
[binding-coap] CoapClientFactory creating client for 'coap'
[core/helpers] WoTImpl fetching TD from 'coap:[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]/.well-known/wot-thing-description' with [CoapClient]
[binding-coap] CoapClient got Form 'contentType' application/td+json
[binding-coap] CoapClient sending GET to coap:[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]/.well-known/wot-thing-description
Fetch error: Error: send EINVAL 2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54:5683
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:429:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'send',
  address: '2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54,
  port: 5683
}
```
I guess the error here is that the IP address is not properly escaped. The parameter should be `[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]:5683` and not `2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54:5683`

### PR DESCRIPTION
**Pull request by Citrullin**
Fixes #363.
Bump versions for packages `node-coap-client` and `coap`. 
`node-coap-client` had an [similar issue with IPv6](https://github.com/AlCalzone/node-coap-client/issues/253). This bump should avoid it in the coaps implementation. 

Not a very nice implementation btw, but it doesn't change the API too much. It keeps everything quite stable. 

**Please test with IPv4. Only tested it with coap on IPv6.**

### CODE REVIEW

**Review by relu91 — CHANGES_REQUESTED** [review]
It feels to me that the server variable is actually just a configuration object. Can we call it `serverConfiguration`? is a bit misleading otherwise. Am I missing something?

**Comment by Citrullin** [comment]
> `serverConfiguration`



> It feels to me that the server variable is actually just a configuration object. Can we call it `serverConfiguration`? is a bit misleading otherwise. Am I missing something?

agentOptions is probably more appropriate, since the class is called agent as well. No, you are not missing anything.

**Review by danielpeintner — APPROVED** [review]

**Comment by danielpeintner** [comment]
> Please test with IPv4. Only tested it with coap on IPv6.

All IPv4 test pass. Looks good.

@relu91 what do you think? Good to go?

**Comment by relu91** [comment]
> agentOptions is probably more appropriate since the class to create the requests is called Agent.

I would like to see this remaining before merging if possible. Sorry for being picky

**Comment by Citrullin** [comment]
> > agentOptions is probably more appropriate since the class to create the requests is called Agent.
> 
> I would like to see this renameing before merging if possible. Sorry for being picky

Done.

**Review by relu91 — APPROVED** [review]

**Pull request merged**
