### PR TITLE
style(http): fix eslint issues

### PR DESCRIPTION
**Pull request by JKRhb**
This PR fixes a number of eslint issues in the `binding-http` package.

### CODE REVIEW

**Comment by relu91** [comment]
I tried to fix all the errors in the src package, we should be almost there. It would be awesome if JKRhb would fix also the remaining issues in the test folder! 🙏🏻

**Comment by JKRhb** [comment]
> It would be awesome if JKRhb would fix also the remaining issues in the test folder! 🙏🏻

Will do :)

**Comment by relu91** [comment]
@JKRhb if you don't mind I'd merge the PR as it is and ask you to create another per for http-tests so that we can move on with #623, is it ok for you?

**Comment by JKRhb** [comment]
Sure, please go ahead :) I will try to provide the follow-up PR shortly.

**Review by danielpeintner — APPROVED** [review]

**Pull request merged**
