### PR TITLE
chore: regenerate package-lock.json for next release

### PR DESCRIPTION
**Pull request by danielpeintner**
I regenerated package-lock to get ready for next release `0.8.1`.

Does this sound reasonable for everyone? We have many minor fixes/improvements and firestore binding is back also.

This makes me think we should publish an update...
@relu91 @sebastiankb @egekorkan

### CODE REVIEW

**Review by relu91 — APPROVED** [review]
Ok for releasing 0.8.1 but please check https://github.com/eclipse/thingweb.node-wot/issues/738

**Comment by relu91** [comment]
On a second thought should we wait for #758?

**Comment by danielpeintner** [comment]
> Ok for releasing 0.8.1 but please check #738

I talked with @egekorkan and @sebastiankb  and we were thinking that sticking to 0.8.1 is better for now.

> On a second thought should we wait for #758?

I don't think this is a blocker and can follow also in 0.8.2.
Moreover, I don't think this will happen within some days. 

Hence , I suggest to publish NOW and publish again if we have some updates.

**Comment by relu91** [comment]
>I talked with @egekorkan and @sebastiankb and we were thinking that sticking to 0.8.1 is better for now.

yes please check my latest comment. let's merge this and release

**Pull request merged**
