### PR TITLE
Codestyle and format

### LINKED ISSUE #239: Inconsistent code style
I'm taking a look at several parts of this project right now and noticed that there are lots of whitespace errors, e.g. indented empty lines and spaces at the end of lines and inconsistencies in code style, e.g. tabs and spaces randomly mixed, even in the same file.

While this isn't a big problem, it means at least two things (to me)
- it's unprofessional. As harsh at it sounds, if a project cannot get these surface level things right, why would it get the actual code right?
- it's confusing. If I'm contributing code, what should it look like? How should it be formatted, structured, etc.

Assuming you agree to this in principle, the question is how to solve this.
Reformatting old code is annoying, because it leads to huge "useless" commits which make version control history harder to use.
For new code or code that's being touched anyways, it's worth thinking about trying to enforce some kind of standard. There are projects like [editorconfig](https://editorconfig.org/) which aim to address this accross different IDEs and editors while also having CI integration with [GitHub actions](https://github.com/marketplace/actions/editorconfig-action) or other systems.

Therefore my proposal would be to leave the old code as-is and introduce an editorconfig and have CI validate against it on PRs.

### PR DESCRIPTION
**Pull request by relu91**
This PR addresses concerns raised in #239. It uses `eslint` and `prettier` as the main tools to achieve a consistent code style across the codebase. I decided to use the standard recommendation of `eslint` but people still can discuss this decision on this PR; once is merged is done. 

This PR is in a draft mode cause:
- I want to give people a chance to discuss it
- I currently limited `eslint` and `prettier` to the core package

Todos:
- [x] Since it is based on #491 first we need to fix the ci tests there
- [ ] Create a ci script verifying that submitted code is well formated. Should we add a new workflow or extend the current one?
- [ ] extends to other packages
- [ ] fix errors 
- [x] fix warnings (?)

Fixes #239 and #243

### CODE REVIEW

**Comment by JKRhb** [comment]
I would say a separate workflow makes sense. This way it should be easier to add, for example, annotations into PR diffs when the codestyle isn't followed. It should also be easier to spot if the CI fails due to a style issue or because of a failing test.

**Comment by danielpeintner** [comment]
I think the PR goes into the right direction 👍 . We need some consistent code style.

Having said that, we do not need to solve "all" in this PR.
i.e., the GitHub script to check can come later etc.

_My_ proposal is to apply the style to all packages and merge...

**Comment by JKRhb** [comment]
I took the freedom of creating both a workflow for running eslint and prettier and would open a PR for that soon which could be merged after this PR.

**Comment by danielpeintner** [comment]
To me it makes perfect sense but I would like to put it in @relu91  hands since he was the original author.

Note: we might take over the todos mentioned in this PR to another to better keep track.

**Comment by danielpeintner** [comment]
@relu91 ready to be merged ... other aspects can come later?

**Comment by JKRhb** [comment]
Maybe the final fixes can also be added in #503 as the linter should already point out what is missing.

**Comment by relu91** [comment]
> Maybe the final fixes can also be added in #503 as the linter CI should already point out what is missing.

yes, why not! 👍🏻 @fatadel can you base your changes on #503? if you already started don't worry we'll merge your changes separately.

**Comment by relu91** [comment]
Ok decided with @danielpeintner to merge this and continue on #503 🎉

**Comment by fatadel** [comment]
> > Maybe the final fixes can also be added in #503 as the linter CI should already point out what is missing.
> 
> yes, why not! 👍🏻 @fatadel can you base your changes on #503? if you already started don't worry we'll merge your changes separately.

Yes, no problem for me 👍🏻

**Comment by danielpeintner** [comment]
@fatadel  branch `v0.8.x` has been merged into `master`.
Hence all PRs from now on should be against  `master`....

**Pull request merged**
