### PR TITLE
Mqtt3/5 binding

### PR DESCRIPTION
**Pull request by johb**
This commit adds support for properties, actions and events over MQTT 3 and 5.
(Not all features are implemented yet)

The BrokerProxy interface was created to be able to use different broker implementations:
Currently the ExternalBrokerProxy is implemented which connects to external brokers.
However, requirements such as Property.Writeable can't be guaranteed with this method.
Therefore an InternalBrokerProxy can be used to expose the broker without external dependencies (WIP).

Problems (so far):
ProtocolServer: How to get informed about changes of a property's value? The ExternalBroker needs to get informed to push new values to mqtt clients.

Note:
The external mqttjs dependency was manually added, since the official version publish via npm lacks mqtt5 support.

### CODE REVIEW

**Comment by danielpeintner** [comment]
Thank you @johb  for your work.

There seem to be issues with the build and you also need to sign the Eclipse agreement.

Any update on Mqtt3/5 binding support is welcome!

**Comment by johb** [comment]
The issue is in package "cli", file "cli-default-servient.ts", the node-wot/binding-mqtt dependency is not found for some reason.

I think this is a problem with lerna?
Binding-mqtt compiles fine, and also all other packages, but cli still can't find the dependency.

I also tried to run npm link/npm unlock like mentioned in the troubleshooting in the readme, still no success.

Do you have any idea?

**Comment by danielpeintner** [comment]
> I think this is a problem with lerna?
> Binding-mqtt compiles fine, and also all other packages, but cli still can't find the dependency.

Mhh, I need do look into it more closely but I see that you export `MqttServer` and `ExternalBrokerProxy` in `mqtt.ts` but if you look at the generated `mqtt.d.ts` file these statements are missing...

Not sure what causes this behavior.

**Comment by danielpeintner** [comment]
Hi @johb!

Great, you found the problem! 

I need to ask you 2 things before we can merge your PR.

1. Resolve the conflicts
2. Sign Eclipse contributor agreement (https://www.eclipse.org/legal/ECA.php)

Thanks!

**Comment by danielpeintner** [comment]
@johb are you still interested in the contribution which is really appreciated!

I run into the ECA issue myself. The *solution* is to actually check whether
1. ECA is signed
2. Use "ECA Validation Tool" to validate the email address
3. Use THIS email address for the commit in your git tool. The same github account is *not* enough

Hope this helps

**Comment by johb** [comment]
@danielpeintner Thanks for the notification, totally missed that there is still a issue with the ECA.

I will open up a new branch soon with the corrected mail address.

**Comment by danielpeintner** [comment]
@johb Thanks!

**Comment by danielpeintner** [comment]
any update @johb ?

**Comment by danielpeintner** [comment]
obsolete due to https://github.com/eclipse/thingweb.node-wot/pull/138

**Pull request closed without merging**
