### PR TITLE
feat: add new example script

### PR DESCRIPTION
**Pull request by fatadel**
Signed-off-by: fatadel <fatadel@gmail.com>

### CODE REVIEW

**Comment by danielpeintner** [comment]
@fatadel Please create the example in TypeScript (see https://github.com/eclipse/thingweb.node-wot/tree/master/packages/examples). Doing so allows us to easily detect if a an example gets out-of-sync with the scripting API, provides type feedback,  et cetera ...

Later you can copy it to https://github.com/eclipse/thingweb.node-wot/tree/master/examples as described in https://github.com/eclipse/thingweb.node-wot/tree/master/packages/examples#workflow

**Comment by fatadel** [comment]
@danielpeintner But that's exactly what I did.

**Comment by danielpeintner** [comment]
> @danielpeintner But that's exactly what I did.

OK great. I might have missed the ts file. Sorry!

**Comment by sebastiankb** [comment]
many thanks for this new Example and Tutorial

**Pull request merged**
