### PR TITLE
Asset Interface Description (AID) Tooling

### PR DESCRIPTION
**Pull request by danielpeintner**
resolves https://github.com/eclipse/thingweb.node-wot/issues/847

### CODE REVIEW

**Comment by danielpeintner** [comment]
I think this PR is now ready to be reviewed.

Besides the tests in the PR itself I will describe how one can try out AID integration.
See following example that describes in AID form the count value of value for http://plugfest.thingweb.io:8083/counter

### 1. Create directory and create the associated sample script plus add file AID_v03_counter.json (is part of this PR)

```JS
// example-client.js

const fs = require('fs/promises'); // to read JSON file in AID format

Servient = require("@node-wot/core").Servient;
HttpClientFactory = require("@node-wot/binding-http").HttpClientFactory;

// AID Util
AssetInterfaceDescriptionUtil = require("@node-wot/td-tools").AssetInterfaceDescriptionUtil;

// create Servient and add HTTP binding
let servient = new Servient();
servient.addClientFactory(new HttpClientFactory(null));

let assetInterfaceDescriptionUtil = new AssetInterfaceDescriptionUtil();

async function example() {
  try {
    const aid = await fs.readFile('AID_v03_counter.json', { encoding: 'utf8' });
	let tdAID = assetInterfaceDescriptionUtil.transformToTD(aid, `{"title": "counter"}`);
	
	const WoT = await servient.start();
	const thing = await WoT.consume(JSON.parse(tdAID));

	// read property count
	const read1 = await thing.readProperty("count");
	console.log("count value is: ", await read1.value());
	
  } catch (err) {
    console.log(err);
  }
}

// launch example
example();
```


### 2. make packages available locally: link vs. install

`npm link @node-wot/td-tools`
`npm link @node-wot/core`
`npm link @node-wot/binding-http`

### 3. run sample 

`node example-client.js`

It will show you the counter value from http://plugfest.thingweb.io:8083/counter/properties/count

**Review by sebastiankb — CHANGES_REQUESTED** [review]
It would be good to have a README for newcomers (e.g., installation details or reference, how to start the js file etc).

**Comment by danielpeintner** [comment]
> It would be good to have a README for newcomers (e.g., installation details or reference, how to start the js file etc).

https://github.com/eclipse/thingweb.node-wot/pull/867/commits/7c173946c66d436ec000865fcbbaca058d1a429d adds a README

**Review by sebastiankb — APPROVED** [review]

**Comment by danielpeintner** [comment]
As requested I provided information about the AID utility and the parameters and created also a section in the main README to provide some basic information about td-tools and links.

**Comment by danielpeintner** [comment]
Approved by @sebastiankb -> merging.

**Pull request merged**
