### PR TITLE
chore: add Node.js 20 and remove Node.js 14 workflow

### PR DESCRIPTION
**Pull request by danielpeintner**
Note: we can also start "thinking" about removing Node.js 14

### CODE REVIEW

**Comment by egekorkan** [comment]
> Note: we can also start "thinking" about removing Node.js 14

Yup we can remove it. We used to keep older versions due to Eclipse server but that is nicely updated to 16 and we can update further if needed.

**Comment by danielpeintner** [comment]
Note: I removed Node.js 14 from GitHub action workflow.
Question: shall we exclude mbus from package.json like we do for firestore till we have a solution?
https://github.com/eclipse/thingweb.node-wot/blob/master/package.json#L41

**Review by relu91 — APPROVED** [review]
Tests are all green I would merge it.

**Comment by danielpeintner** [comment]
Interesting. The test used to fail because of issues with mbus but they seem to be gone after i restarted the workflow.

@egekorkan you noticed the same issues with mbus and Node.JS 20.
Can you check whether they are gone on our side as well

**Comment by egekorkan** [comment]
> Interesting. The test used to fail because of issues with mbus but they seem to be gone after i restarted the workflow.
> 
> @egekorkan you noticed the same issues with mbus and Node.JS 20. Can you check whether they are gone on our side as well

Yes it is gone as well

**Comment by danielpeintner** [comment]
The workflow now refuses to run
see https://github.com/eclipse/thingweb.node-wot/actions/runs/4960136649

Let's see whether this issue is just the case for this specific case

**Comment by JKRhb** [comment]
> The workflow now refuses to run see https://github.com/eclipse/thingweb.node-wot/actions/runs/4960136649
> 
> Let's see whether this issue is just the case for this specific case

Hmm, I think there is an opening square bracket missing in the workflow file.

**Comment by relu91** [comment]
Some how we got a greenlight from Github but he didn't actually run CI. Something we have to look after next time :/

**Pull request merged**
