### PR TITLE
Issue interaction input to readable

### PR DESCRIPTION
**Pull request by danielpeintner**
see https://github.com/eclipse/thingweb.node-wot/issues/482#issuecomment-966497766

### CODE REVIEW

**Comment by relu91** [comment]
I'm not sure if this is really needed after #623

**Comment by danielpeintner** [comment]
> I'm not sure if this is really needed after #623

Great. Anyhow, we should add a test with object/array as the once in this PR to check for it besides simple types.

**Review by relu91 — APPROVED** [review]
Ah ok, now I got why we create the PR anyway. Is the name of the test correct? It feels a little bit obscure to me. What about:
> "should serialize objects for actions and properties"

**Comment by danielpeintner** [comment]
> Ah ok, now I got why we create the PR anyway. Is the name of the test correct? It feels a little bit obscure to me. What about:
> 
> > "should serialize objects for actions and properties"

👍

**Pull request merged**
