### PR TITLE
feat(binding-websockets): add handlers for properties and actions

### PR DESCRIPTION
**Pull request by miguelrk**
**NOTE: this PR replaces #480 made to old `master` branch before `v0.8` merge**

This PR adds (provisional) support for properties and actions (see #476). From here we can continue implementing a websocket subprotocol as described in #476 and taking both the discussions over at [wot-profile](https://github.com/w3c/wot-profile) and [Web Thing Protocol](https://iot.mozilla.org/wot/#web-thing-websocket-api) into consideration.

Regarding testing, I couldn't get it to work on my machine (throwing several build errors). Code might therefore need some refinement but I decided to push anyways as to progressively work on (and test) this PR.

### CODE REVIEW

**Comment by miguelrk** [comment]
BTW: recent style/formatting updates worked great! The previous whitespace noise is thus gone without extra dev effort.

**Comment by danielpeintner** [comment]
Thanks @miguelrk !
Do you think you can also provide a test? I know there is no *real* websocket test so far 🙈

**Comment by miguelrk** [comment]
> Do you think you can also provide a test? I know there is no _real_ websocket test so far

I'd be happy to! I don't have much time as of late though, but I'll keep you posted 👍🏼

**Comment by danielpeintner** [comment]
@miguelrk do you prefer to do it in a follow-up PR?

Also fine by me. So we can get the content in and tests come later?

Note: I see a conflict for this PR.

**Comment by miguelrk** [comment]
@danielpeintner I wouldn't mind. Whatever is best is fine by me

**Comment by danielpeintner** [comment]
> @danielpeintner I wouldn't mind. Whatever is best is fine by me

I think this depends on your timeline. If you need more time for the tests I would be in favor of merging this PR now otherwise we are always running into conflict issues that just cause unnecessary work.

Having said that, I think resolving the conflict and merging now is fine.

**Comment by miguelrk** [comment]
Great! As I said, I'm not so sure when I will be able to provide the tests, hopefully soon since I want to give the Websocket subprotocol a go as well. I could provide them later on a separate PR, if that makes sense 👍🏼

**Comment by danielpeintner** [comment]
Great than lets postpone the tests.

@miguelrk may I ask you to resolve the conflict for ws-server.ts. Before that we cannot merge. Thanks!

**Comment by relu91** [comment]
FYI: I just solved the conflicts, let's wait for CI to complete than we can merge it 👍🏻

**Review by danielpeintner — APPROVED** [review]

**Comment by miguelrk** [comment]
Great! Thanks @relu91! 🙌🏻 Hadn't had time to get to it

**Pull request merged**
