### PR TITLE
chore(binding-http): add HTTP examples from README as files

### PR DESCRIPTION
**Pull request by danielpeintner**
follow-up PR for https://github.com/eclipse/thingweb.node-wot/pull/742

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: I noticed that `npm run build` for `packages/examples` is not run by `npm run build` in root folder (meaning that there can be code that does not compile).
Is there any reason for that? Shall we change that? I would say so...
@relu91 @JKRhb @erossignon

**Comment by JKRhb** [comment]
I think there were some issues initially with the examples package that have been resolved in the meantime, so I would also be in favor of including the package in the build script :)

**Comment by danielpeintner** [comment]
Since we got 👍's I added `packages/examples` again to build path. I think this PR is now ready for review...

**Comment by danielpeintner** [comment]
Since we got 👍's I added `packages/examples` again to build path. I think this PR is now ready for review...

**Review by relu91 — APPROVED** [review]

**Pull request merged**
