### PR TITLE
feat(http-server): implement TD content negotiation

### PR DESCRIPTION
**Pull request by JKRhb**
This PR implements a simple content negotiation mechanism for the HTTP binding and adds two ~an~ additional tests. In the process, I applied some refactoring to the language negotiation code.

### CODE REVIEW

**Review by danielpeintner — APPROVED** [review]
Thank, LGTM 👍 

The only thing I would have done is to split the test into 2 tests.
1 for success and 1 for fail but I can also live with it as is ;-)

**Comment by JKRhb** [comment]
> Thanks, LGTM 👍
> 
> The only thing I would have done is to split the test into 2 tests. 1 for success and 1 for fail but I can also live with it as is ;-)

Thank you for the feedback, should be adjusted now :)

**Comment by danielpeintner** [comment]
Great, thanks!
Let's give @relu91 some time to look at the PR as well

**Review by relu91 — APPROVED** [review]
Awesome, let's merge this (thank you also for refactoring!! 🥳 )

**Pull request merged**
