### PR TITLE
Protocol binding for Modbus/TCP - Second candidate

### PR DESCRIPTION
**Pull request by wiresio**
Protocol binding for Modbus/TCP - Second candidate

Signed-off-by: Christian Glomb <christian.glomb@siemens.com>

### CODE REVIEW

**Comment by wiresio** [comment]
**Feature comparison**

| Feature  | relu91  | wires.io  |
|---|---|---|
| Encoding of Modbus function  | New modbus:function and modbus:entity field in form  | URL  |
| Register number  | New modbus:range field in form  | URL  |
| Unit ID  | modbus:unitID  | URL  |
| Subscriptions  | modbus:pollingTime  | not implemented  |
| Timeout  | modbus:timeout  | not implemented  |
| Protocol URL  | modbus://  | modbus+tcp://  |
| Connection pooling  | TODO  | yes  |
| Register pooling  | no  | yes  |
| Conversion based on DataSchema  | no  | yes  |
| Tests  | yes  | no  |

- Connection pooling: use open connection for multiple requests instead of always opening a new one
- Register pooling: Merge requests for registers that are next to each other - increases performance

**Comment by relu91** [comment]
Thank you @wiresio for the detailed analysis of the two PRs. It is great that you implemented register and connection pooling. I guess the twos could be merged together. I can volunteer for merging them after I finished my work on oAuth2 (a draft PR is almost ready). 

Just a couple comments:
- modbus+tcp:// protocol schema is more correct, thanks to pointing that out
- `modbus:range`, `modbus:function` and `modbus:entity`, in my opinion, are more expressive than encoding them in the URL (of course is more verbose). Also, following a RESTfull like approach methods should not be encoded in URLs (i.e. modbus function).
- modbus:unitID instead make more sense to be URL encoded (like is done for RESTfull applications)

**Comment by wiresio** [comment]
@relu91 - I fully agree to your comments - and many thanks for volunteering!

**Comment by danielpeintner** [comment]
Closed in favor of PR https://github.com/eclipse/thingweb.node-wot/pull/186

**Pull request closed without merging**
