### PR TITLE
Introduce new subscription APIs in ConsumedThing

### PR DESCRIPTION
**Pull request by relu91**
This PR, once completed, will align the `ConsumeThing` interface with the [current specification](https://w3c.github.io/wot-scripting-api/#the-consumedthing-interface). This mainly consists of the refactoring of the subscription API, as described in #583. 

I'm putting this in draft cause I don't properly tested the changes. But if you want already review it you're welcome to provide your feedback!.

### CODE REVIEW

**Comment by relu91** [comment]
Besides some concerned raised in w3c/wot-thing-descriptio#968 this PR should be ready to be reviewed/tested/merged :)

**Review by danielpeintner — APPROVED** [review]
LGTM

let's figure out the next steps in  https://github.com/w3c/wot-thing-description/issues/968

**Comment by danielpeintner** [comment]
@relu91 we missed to merge the PR and we do have conflicts now. Can you look into?

**Comment by relu91** [comment]
Conflicts fixed, I think is time to merge it :)

**Pull request merged**
