### PR TITLE
use drop-downs

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse/thingweb.node-wot/issues/671

see [rendered](https://github.com/eclipse/thingweb.node-wot/blob/0ffbf3aa61e130387ffff76ec15348b8ec3736b9/README.md) version.

### CODE REVIEW

**Review by relu91 — APPROVED** [review]
LGTM

**Comment by danielpeintner** [comment]
I noticed 2 issues with drop-downs.

* the hamburger  menu (mentioned  by @JKRhb) only works IF teh content it is visible (drop-down needs to be open)
* the hamburger misses the the entry / level for the dropdown header... I think we would need to add this level back, i.e.` ### MediaType Support` 

any opinions?

grafik

**Comment by relu91** [comment]
> the hamburger misses the the entry / level for the dropdown header... I think we would need to add this level back, i.e. ### MediaType Support

Something like this? 

## Implemented/supported features
### Protocol Support
<details>
<summary>content</summary>
<br>

-   [HTTP](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/README.md) :heavy_check_mark:
-   [HTTPS](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/README.md) :heavy_check_mark:
-   [CoAP](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/README.md) :heavy_check_mark:
-   [CoAPS](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/README.md) :heavy_check_mark:
-   [MQTT](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-mqtt/README.md) :heavy_check_mark:
-   [Firestore](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-firestore/README.md) :heavy_check_mark:
-   [Websocket](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-websockets) :heavy_plus_sign: (Server only)
-   [OPC-UA](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-opcua/README.md) :heavy_plus_sign: (Client only)
-   [NETCONF](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-netconf/README.md) :heavy_plus_sign: (Client only)
-   [Modbus](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-modbus) :heavy_plus_sign: (Client only)
-   [M-Bus](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-mbus) :heavy_plus_sign: (Client only)

Note: More protocols can be easily added by implementing `ProtocolClient`, `ProtocolClientFactory`, and `ProtocolServer` interface.

Note: the bindings for [binding-fujitsu](https://github.com/eclipse/thingweb.node-wot/tree/v0.7.x/packages/binding-fujitsu) and [binding-oracle](https://github.com/eclipse/thingweb.node-wot/tree/v0.7.x/packages/binding-oracle) were removed after `v0.7.x` due to lack of maintainers.

</details>

> the hamburger menu (mentioned by @JKRhb) only works IF teh content it is visible (drop-down needs to be open)

I don't think this would be a big issue IF we solve the second issue like the above.

**Comment by danielpeintner** [comment]
@relu91 right something like you proposed. will update PR.

Are you okay with "more" or "details" instead of "content" also?

**Comment by relu91** [comment]
> Are you okay with "more" or "details" instead of "content" also?

yes, way better 👍🏻

**Comment by danielpeintner** [comment]
please have a look at the [new version](https://github.com/eclipse/thingweb.node-wot/blob/5e8457f27572a05fd74b132099b7c9d9e092f819/README.md).

* TOC has been removed
* headers are now outside  the details sections

**Review by relu91 — APPROVED** [review]

**Pull request merged**
