### PR TITLE
Fix 439

### PR DESCRIPTION
**Pull request by relu91**
A minor fix for issue #439. Now the Modbus client properly initializes the connection with the right timeout. Plus this PR also adds a convenient launch task to debug the Modbus test suite.

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: test fail seems unrelated, is about MQTT

**Review by danielpeintner — APPROVED** [review]
LGTM, but I am not very familiar with Modbus.

@LennyHEVS can you check also?

**Comment by LennyHEVS** [comment]
The changes are good and seem to be working nicely.

But it exposed another problem. When closing the unused connection fails (with a TCP timeout for example), the flag `connected` of `ModbusConnection` cannot be trusted anymore. For futur requests, I suggest using the `this.client.isOpen` instead of `this.connected` to check the connection.

**Comment by relu91** [comment]
> But it exposed another problem. When closing the unused connection fails (with a TCP timeout for example), the flag connected of ModbusConnection cannot be trusted anymore. For futur requests, I suggest using the this.client.isOpen instead of this.connected to check the connection.

That's a good point, my assumption was that if the `close` method fails then the connection is actually not fully closed, therefore connected -> `true`. Do you think we should revisit this implementation? maybe it might worth assigning the underlying `this.client.isOpen` to `this.connected`. What do you think?

**Comment by LennyHEVS** [comment]
What I saw in the library is that if a callback method is called, the callback function pointer is then set to `null` in the `modbus-serial` library. I noticed that a TCP Timeout could occur between the call of the `close` method and the time when port actually closes.

> That's a good point, my assumption was that if the `close` method fails then the connection is actually not fully closed, therefore connected -> `true`.

In this case, closing does not fail but we will not be able to catch the "on close" signal afterwards. In the timeout callback, the port is still open, which makes assigning `this.client.isOpen` to `this.connected` obsolete after the "on close" signal.

> Do you think we should revisit this implementation? maybe it might worth assigning the underlying `this.client.isOpen` to `this.connected`. What do you think?

Completly revisiting the implementation might be too much of a task. What I think would be great is if we could ensure that the state of the connection at all time. Therefore we will be able to connect/reconnect/close the connection when needed.

**Comment by relu91** [comment]
Sorry @LennyHEVS are you saying that this: 
```ts
 private modbusstop() {
    console.debug('[binding-modbus]', 'Closing unused connection');
    this.client.close((err: string) => {
      if (!err) {
        console.debug('[binding-modbus]', 'session closed');
        this.connecting = false;
        this.connected = this.client.isOpen;
      } else {
        console.error('[binding-modbus]', 'cannot close session ' + err);
      }
    });
    clearInterval(this.timer)
    this.timer = null;
  }
```

Would not work? Sorry I might get a little lost cause I don't remember too much about the internals of Modbus TCP library.

**Comment by LennyHEVS** [comment]
> Would not work? Sorry I might get a little lost cause I don't remember too much about the internals of Modbus TCP library.

Yes, unfortunatly `this.client.isOpen` will return `true` if the callback arrives before the `close` signal.

**Comment by LennyHEVS** [comment]
An easy fix would be to get rid of the flag `connected` and to replace the lines
```Javascript
96    if (!this.connecting && !this.connected) {
with
96    if (!this.connecting && !this.client.isOpen) {
```
,
```Javascript
129    if (!this.connecting && !this.connected) {
with
129    if (!this.connecting && !this.client.isOpen) {
```
and
```Javascript
144    } else if (this.connected && this.currentTransaction == null && this.queue.length > 0) {
with
144    } else if (this.client.isOpen && this.currentTransaction == null && this.queue.length > 0) {
```
But I don't know if you want to keep this flag and what happens then with the `connecting` flag

**Comment by relu91** [comment]
@LennyHEVS Thank you for expanding! I think it makes more sense to not trying to introduce another variable to keep in sync with isOpen. Plus all the tests are green so I think we'll not miss `this.connected`

**Comment by relu91** [comment]
Given the thumbs up by @LennyHEVS, I'd wait for the final approval by @danielpeintner and then merge 🥳

**Pull request merged**
