### PR TITLE
Introduce InteractionOutput

### PR DESCRIPTION
**Pull request by relu91**
This PR is based on @danielpeintner's work [here](https://github.com/eclipse/thingweb.node-wot/pull/381). In particular, it changes the returned object of ConsumedThing interactions to InteractionOutput. There are still some minor issues to consider but since it is a major change I'd like to gather feedback as soon as possible. I'd ask reviewers to focus on the newly added class and the changes in the core's dependencies.

### CODE REVIEW

**Comment by danielpeintner** [comment]
@relu91 Thanks for your work.
It looks good to me and I suggest we merge this PR soon.. so that we can move on from there again...

Some thoughts questions
* Most of the package.json changes are no-changers (anyhow I am fine with it)
* iteraction-ouput.ts --> fix typo in file-name
* Question: do we want to keep the interface Content as it is currently sketched or do we plan further updates, see https://github.com/eclipse/thingweb.node-wot/issues

**Comment by relu91** [comment]
Hi, Daniel
Sorry for the type I'll fix it in seconds. About the package.json probably npm install reorder the dependencies... I am sorry for the "noise". 

The Content interface is the reason because this PR is still in draft. While coding I was not sure if it was the best we could do. Do you have some points about how to improve it? your link simply points to the issue list.

**Comment by danielpeintner** [comment]
> Sorry for the type I'll fix it in seconds.

👍 

> About the package.json probably npm install reorder the dependencies... I am sorry for the "noise".

I wouldn't mind much but I recall that merging this branch with master or merge master into the current branch caused a lot of troubles last time. Do you think we can revert the unnecessary changes?

> The Content interface is the reason because this PR is still in draft. While coding I was not sure if it was the best we could do. Do you have some points about how to improve it? your link simply points to the issue list.

Sorry, missed the actual issue...
I suggest to discuss this further in issue https://github.com/eclipse/thingweb.node-wot/issues/382

**Comment by relu91** [comment]
fixed the issue @danielpeintner mentioned. Notice the project will not build because this PR didn't involve changes at the example level. As I said in other comments, we should fix the examples as the last step of the implementation of the new API. 

"A day may come when we'll fix the examples, but it is not THIS day" .cit

**Review by danielpeintner — APPROVED** [review]
I am OK with merging. @relu91 can I remove the WIP label and go ahead doing so?
As you mentioned other updates can come later...

**Comment by relu91** [comment]
yes please.

**Pull request merged**
