### PR TITLE
Modbus client protocol binding - First Candidate

### PR DESCRIPTION
**Pull request by relu91**
This PR introduces another protocol binding to thigweb.node-wot. I made some experience with Modbus and I thought that this repo could benefit from this. I followed the guidelines of the other implementations and I made some tests to verify the correct behavior of the library.

Modbus is a pretty old protocol but it is quite well spread in the industry, I am using this URL syntax as form href: "modbus://address:port". I saw that it already used around but I cannot find a formal definition of modbus:// prefix. Anyway, it should work for this purpose.

### CODE REVIEW

**Comment by relu91** [comment]
I changed back the title to [WIP]because after the merge with @wiresio PR I'd like to make some refactoring in a couple of days. 

Meanwhile, there are some problems with @wiresio commits. Any suggestions on how to fix them? after this merge, would it be possible to sign every commit?

**Comment by danielpeintner** [comment]
> Any suggestions on how to fix them?

Mhh, not sure if it works but maybe you can try to squash all commits into one. Not sure though if that resolves the issue.

**Comment by relu91** [comment]
It might work, but I am wondering if we are going to lose all @wiresio contribution history... 🤔 the squashed commit will be authored only by me...

**Comment by wiresio** [comment]
@relu91, @danielpeintner  - no worries about this, please go ahead with the best "technical" solution.

**Comment by relu91** [comment]
I squashed the commits and also managed to maintain the authorship of @wiresio. As I said in the previous comment, please wait to merge.

**Comment by danielpeintner** [comment]
@relu91 ready for review, correct?

@wiresio may I ask you to take a look?

**Comment by relu91** [comment]
yes! green light from my side 👍

**Comment by wiresio** [comment]
@relu91 - Thanks again for this contribution at which I finally found time to take a look at.
Here are some finding when trying to run the example app:
- The optional `sudo npm run link` in the node-wot parent folder seems to be a precondition to run the example such that `npm install` in folder examples/servients/modbus-cli/ works.
- hrefs in modbus-thing.jsonld must be changed from 'modbus' to 'modbus+tcp' to run the client.
- However, then I got stuck with the following message:
`ModbusClientFactory creating client for 'modbus+tcp'`
`ConsumedThing 'Modbus TestThing' got new client for 'modbus+tcp'`</br>
`ConsumedThing 'Modbus TestThing' setting credentials for [object Object]`</br>
`Servient looking up credentials for 'urn:dev:wot:org:eclipse:modbus-example'`</br>
`ConsumedThing 'Modbus TestThing' writing modbus+tcp://127.0.0.1:60000 with 'true'`</br>
`ContentSerdes serializing to application/octet-stream;length=1`</br>
`Application error: Cannot read property 'type' of undefined`</br>

**Comment by relu91** [comment]
@wiresio thank you really much for your review. 

>The optional sudo npm run link in the node-wot parent folder seems to be a precondition to run the example such that npm install in folder examples/servients/modbus-cli/ works.

Right, I'll state this dependency in the README

> hrefs in modbus-thing.jsonld must be changed from 'modbus' to 'modbus+tcp' to run the client.

Thank you I forgot to update them.

>However, then I got stuck with the following message:
ModbusClientFactory creating client for 'modbus+tcp'
ConsumedThing 'Modbus TestThing' got new client for 'modbus+tcp'
ConsumedThing 'Modbus TestThing' setting credentials for [object Object]
Servient looking up credentials for 'urn:dev:wot:org:eclipse:modbus-example'
ConsumedThing 'Modbus TestThing' writing modbus+tcp://127.0.0.1:60000 with 'true'
ContentSerdes serializing to application/octet-stream;length=1
Application error: Cannot read property 'type' of undefined

This here is a little bit tricky. It seems to be caused by [this line](https://github.com/danielpeintner/thingweb.node-wot/commit/ea3273203ce2a6017e022106aa5091c20a341630#diff-babad2a8213f8de6110b0c5108065ab6R234) and it is related to @danielpeintner 's commit 
ea32732 . The commit metion a issue were it was asked to change how the DataSchema is passed to the contentManager for Actions but it actually changed the value inside the `writeProperty` function. I am not sure if this is intended or an error. I can fix it but first I have to be sure that is an error. 

After that I'll test again the example and see if everything runs.

**Comment by danielpeintner** [comment]
> This here is a little bit tricky. It seems to be caused by [this line](https://github.com/danielpeintner/thingweb.node-wot/commit/ea3273203ce2a6017e022106aa5091c20a341630#diff-babad2a8213f8de6110b0c5108065ab6R234) and it is related to @danielpeintner 's commit
> [ea32732](https://github.com/eclipse/thingweb.node-wot/commit/ea3273203ce2a6017e022106aa5091c20a341630) . The commit metion a issue were it was asked to change how the DataSchema is passed to the contentManager for Actions but it actually changed the value inside the `writeProperty` function. I am not sure if this is intended or an error. I can fix it but first I have to be sure that is an error.

I am sorry, you are right!

I wanted to fix the` ContentManager.valueToContent()` call for actions and did update it for property. I will provide a fix.

**Comment by danielpeintner** [comment]
@relu91 please take a look at PR https://github.com/eclipse/thingweb.node-wot/pull/263 

I think this time the fix should be OK :-(
I can merge the PR once you have time to look at it and you can approve that it works

**Comment by relu91** [comment]
Now everything works again 👍.  

BTW:
>The optional sudo npm run link in the node-wot parent folder seems to be a precondition to run the example such that npm install in folder examples/servients/modbus-cli/ works.
Right, I'll state this dependency in the README

This was already mentioned in the readme:

> **Rember** to correctly initialize your dev environment as described inside the [repository readme](../../README.md), before to start the example application.

Could it be clearer?

**Comment by wiresio** [comment]
> Could it be clearer?

Yes, because in the readme that you are mentioning `sudo npm run link` is an optional step (that I usually do not execute). Maybe it is a very minor detail.

**Comment by relu91** [comment]
> Yes, because in the readme that you are mentioning `sudo npm run link` is an optional step (that I usually do not execute). Maybe it is a very minor detail.

Done! thanks for the input 👍

**Comment by danielpeintner** [comment]
@wiresio ok to merge? Can you "push" the approve button if so ;-) 

We gonna close PR https://github.com/eclipse/thingweb.node-wot/pull/194 in favor of this, correct?

**Pull request merged**
