### PR TITLE
Setup information for WSL users

### PR DESCRIPTION
**Pull request by joshco**
see #207

### CODE REVIEW

**Comment by danielpeintner** [comment]
@joshco thank you for the PR. Content-wise it looks good to me.

Since this is a Eclipse project you need to sign the Eclipse Contributor Agreement (ECA). May I ask you to do so....

**Comment by joshco** [comment]
Already done.  user jcohenko7

**Comment by relu91** [comment]
To solve the errors you should also add a signature footer in your commits. if you correctly configure your email in your git globals `git config user.email "<your Eclipse account email>"`, you just need to run `git commit --amend -s`. Then push again on this branch (maybe you need to add -f to force the push operation).

**Comment by joshco** [comment]
I created the commit and PR via the github web UI.  My github email is the same as my eclipse account. 
 However, I created my eclipse account and signed the agreement about 2 minutes before I did these things so maybe it's not instantaneous.

**Comment by joshco** [comment]
Wait, I'm reading the docs more carefully...

**Comment by danielpeintner** [comment]
The tooling shows "passed" now. Thanks!

**Pull request merged**
